name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

   steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker buildx build -t hello .

      - name: Log in to Huawei Cloud SWR
        uses: huaweicloud/swr-login@v2.1.0
        with:
          access-key-id: ${{6BLHJIM4UAZ3RVTBVLSA}}
          access-key-secret: ${{r0GShaF8STlK6LxkFERE2AUMmaZNjQKACranDZ4y}}
          region: af-south-1

      - name: Build and push Docker image
        run: |
          docker build -t swr.af-south-1.myhuaweicloud.com/martin/hello-world-nodejs:${{ github.sha }} .
          docker push swr.af-south-1.myhuaweicloud.com/martin/hello-world-nodejs:${{ github.sha }}

